version: '3.7'

services:
    build_apk:
        image: getinkstone/inkstone-buildenv
        build:
            context: .
            cache_from:
                - getinkstone/inkstone-buildenv
        volumes:
           - .:/project
        entrypoint: /project/scripts/build
