name: inkstone

on:
  - push
  - pull_request


jobs:
  maybe_update_meetup:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: try to pull the image
      run: docker-compose pull || true
    - name: build using docker-compose
      run: docker-compose up
