name: inkstone

on:
  - push
  - pull_request


jobs:
  build_apk:
    if: "!contains(github.event.head_commit.message, 'skip ci')"
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: try to pull the image
      run: docker-compose pull || true
    - name: build using docker-compose
      run: docker-compose up
